### ISSUE TITLE
1.19.3?

### ISSUE THREAD

**Issue by Aces-and-Jacks** [Voxxin/colour-my-servers#2]

**Comment by Voxxin** [comment]
It should work already! 
It's not specifically written anywhere. But it works for me.

**Comment by Aces-and-Jacks** [comment]
sorry I forgot to paste this "Do you plan on updating the mod, and if it already works would you be able to mark it on modrinth?" when I was going to different mods about it. 

Would you be able to update the tag on modrinth if it works then?

**Comment by Voxxin** [comment]
Oh you're right! I marked it for my other mod and forgot to do it fro CMS. Thank you for bringing it to my attention :)

**Comment by Voxxin** [comment]
Now marked! Thanks again.
